### ISSUE TITLE
No module named 'gi'

### ISSUE THREAD

**Issue by murnux** [JannikHv/gydl#1]
Hope I'm not missing something obvious here, but Python throws out an error saying there is no module named gi.

`Traceback (most recent call last):
  File "gydl.py", line 3, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
`

This is with Python 3.6 on Arch Linux.

**Comment by JannikHv** [comment]
I hope you fixed yourself, you close this issue pretty rapidly :P.

For others to read how you fixed:

There was a missing dependency, Python-Gobject. On Arch you install it by:

    $ sudo pacman -S python-gobject

on Ubuntu it'd be:

    $ sudo apt install python3-gi

**Comment by arch-linux-tux** [comment]
Running `$ sudo pacman -S python-gobject` on Arch Linux did not work for me.

But I found a working solution on askubuntu.com (which also works on Arch Linux):
Just change `#!/usr/bin/env python` to `#!/usr/bin/python` in `/usr/bin/gnome-tweak-tool` file - done!

I hope this helps those for whom the first solution by JannikHv doesn't work.

_References:_
[1] https://askubuntu.com/a/106454/358665
[2] https://ubuntuforums.org/showthread.php?t=1909933&s=ed0ffd85c06037a61271068de9459907&p=11624982#post11624982

**Comment by olivertzeng** [comment]
> /usr/bin/gnome-tweak-tool
i dont have that file

**Comment by olivertzeng** [comment]
@ArchetypeLinuxTux
