### ISSUE TITLE
AUR package is missing deps and/or not working

### ISSUE THREAD

**Issue by vankasteelj** [JannikHv/gydl#13]
Hi, the packager @AffeAli didnt leave any other link than this. It simply doesn't work on Manjaro KDE (20/09/2017), says "Plasma: Unable to find gydl application"

**Comment by AsavarTzeth** [comment]
Are you referring to this [package](https://aur.archlinux.org/packages/gydl-git/)? If you suspect it is a packaging issue you should report it in the comment section on the AUR site.

The app itself seems to work on my Arch Linux installation. However the command to launch it is back to being `gydl.py` in favor of just `gydl`, while the desktop entry file still uses `Exec=gydl`. I could see this change being necessary.

**Comment by AsavarTzeth** [comment]
I committed a simple fix that should resolve the issue.
