### ISSUE TITLE
Gydl vanishes until the download gets finished and then pops up with the result

### ISSUE THREAD

**Issue by BharatKalluri** [JannikHv/gydl#14]
I am using Gydl with flatpak. I don't know if this is intentional but whenever download gets clicked, the window just closes and after some time, it pops up with the status.

**Comment by JannikHv** [comment]
As for now, it is intentional. Looking for a way around this though.

**Comment by BharatKalluri** [comment]
Shall I add a spinner indicating that the file is downloading so that we can keep the window open?

**Comment by JannikHv** [comment]
You can try that and make a pull request, I'd appreciate that. The only problem for me was to determine when the (shell) command has finished (either successfully or not) since just running the command entirely stops GTK+ from working.
