### ISSUE TITLE
Missing documentation about audio quality

### ISSUE THREAD

**Issue by tuxutku** [JannikHv/gydl#16]
![screenshot](https://user-images.githubusercontent.com/24626743/36379630-6af0ca2c-1590-11e8-8fa1-efd96d841d6a.png)
what does the quality level do? (like what is the specific quality selection at each level and is it 0 or 9 is the best quality?)

[audio_samples.zip](https://github.com/JannikHv/gydl/files/1736836/audio_samples.zip)

files in it:
work0.mp3 --> audio sample with option 0 chosen 
work1.mp3 --> audio sample with option 1 chosen 
work9.mp3 --> audio sample with option 9 chosen 

as i look to codec information audio quality and size comparison was 0>1>9
```
[utku@utku ~]$ uname -a
Linux utku 4.15.3-2-ARCH #1 SMP PREEMPT Thu Feb 15 00:13:49 UTC 2018 x86_64 GNU/Linux
```
Antergos installation with xfce desktop, 64 bit

**Comment by JannikHv** [comment]
Going to add this to the README soon, thanks for bringing this to my attention.

Marking this as solved as soon as I did so.

**Comment by p3732** [comment]
I think just putting it in the README will not help much for people simply using gydl (and not compiling it themselves).

How about renaming the dropdown menu items to "0 (Best)", 1, 2, 3, 4, 5 (Average), 6, 7, 8, 9 (Smallest). Also I would assume it's a good idea to default to 0.

**Comment by JannikHv** [comment]
Thanks for the pull request! I'll later adopt the changes in the C-Rewrite.
