### ISSUE TITLE
Download looks successful but file is no where insight

### ISSUE THREAD

**Issue by drpeppercan** [JannikHv/gydl#19]
I could provide back log info if I knew what command lines I need.
I will post it here if someone sends me those command lines.
Ubuntu 18.04

**Comment by JannikHv** [comment]
Gydl will always try to use your download folder. If your downloaded file is not in `~/Downloads` and no error dialog was shown then I'd like you to run Gydl from command line with `gydl`, download something again and report back what was prompted to the terminal.

**Comment by JannikHv** [comment]
Feel free to re-open if needed.
