### ISSUE TITLE
Return to main screen when finished

### ISSUE THREAD

**Issue by LiamDawe** [JannikHv/gydl#5]
Currently the application quits when finished, but it would be useful to have it return to the main screen.

**Comment by JannikHv** [comment]
It's implemented now https://github.com/JannikHv/gydl/commit/74a38d1c9fe9d8289cef962e908ed37445a0e87a .

When pressing on "Done" you now return to the applications main screen. The former Image on the dialogs top left corner is now made into a button (with the "Exit" label) to completely quit. Hope that helps, let me know if you have any other great ideas :)

**Comment by LiamDawe** [comment]
Fantastic 👍
