### ISSUE TITLE
Application specific icon (for Flatpak)

### ISSUE THREAD

**Issue by AsavarTzeth** [JannikHv/gydl#6]
I have been packaging your application as a Flatpak, which I intend to upload to [Flathub](https://github.com/flathub). As of now I have everything working properly but flatpak-builder refuses to export the desktop entry file because an icon is required.

Because I don't want to misrepresent you or anyone else I felt I must bring the issue to you directly.

So I ask, is there any possibility of you providing an official icon to represent the application? If not, could someone else do it for you? Or do you have another solution?

If you don't have the time and nobody else comes along I would be willing to give it a try, although I am quite inexperienced.

**The icon should be a scale-able SVG.**

**Comment by JannikHv** [comment]
First of all, I think it's very lovely of you to do that.

It's perfectly fine to ask this here, though I think I must dissapoint you. So if I understand you correctly, you want an icon, exclusively for Gydl?

I think I can make this happen in near future, although you should know, that there is currently the plan of a complete rewrite in C since Python doesn't seem to be a fitting language in this project.

If any questions remain, feel free to ask me :)

**Comment by AsavarTzeth** [comment]
Thank you for your answer, I had no disillusions about a quick answer and I had already guessed that you are busy with studies.

Yes you understand correctly. Specifically, without a dedicated icon whose filename matches the application id `flatpak-builder` won't export any desktop entry files.

In other words, without an icon you would have to launch application with `flatpak run com.github.JannikHv.Gydl` on the command line, which isn't very user friendly.

Regarding the rewrite, I don't think that's a big issue. Your application has a minimal set of dependencies so I don't expect updating the flatpak manifest file would be that difficult.

I suppose there is one question related to license complications when bundling dependencies, but that can wait. I certainly would not want that brought to me when I am already stressed :)

**Comment by JannikHv** [comment]
That's very kind of you, thanks for your sympathy.

Yeah I can relate to that.

Yes, I neither think so, you still only need GTK+-3.0 and youtube-dl installed.

Well, I atleast *hope* that can wait a little ;) The stress is slowly but surely going away now though, having holidays in a few days where I can fully dedicate my focus on Gydl.

Tomorrow I'm going to approach the Gydl icon creation, I've got a few people in mind which are quite talented.

Thanks for all of your support man!

**Comment by AsavarTzeth** [comment]
Just for fun I have spent the last few days learning Inkscape. I made a lot of crappy icons!

At first I wanted to capture the fact that it downloads from a lot of sites and that it can transcode into audio. So I tried to fit a player triangle, musical note and a download arrow. This turned out to be at least one object too many.

In the end I managed to make something I am happy with. It is a really basic design, that follows the typical youtube downloader apps. It makes it harder to stand out, but on the other hand it is probably what users expect to see.

https://imgur.com/a/9sWRl

**Comment by AsavarTzeth** [comment]
With the recent commit access you gave me I assumed it was okay to at least push a place holder icon. If it turns out good enough to use in the long run, that would make me happy. If not, that is okay as well.

At least now we can publish this on Flathub so users have a stable release they can use until the new version of Gydl is ready.

In other words, it brings you some breathing room.

**Comment by JannikHv** [comment]
Yes, totally fine. You are/were such a great assistance, especially as I had many personal problems holding me back from working on Gydl, thanks for that, really. I'm happy to keep working with you on this project :)
