### ISSUE TITLE
Can't seem to get anything to download.

### ISSUE THREAD

**Issue by DroWnThePoor** [JannikHv/gydl#7]
Perhaps I'm doings something wrong, but whenever I attempt to download a video through the application It always gives the error Download Uncuccessful with no other relevant information. Perhaps I'm missing some relevant step.
I'm running the app through the terminal and the only output is
/bin/sh: 1: youtube-dl: not found

**Comment by JannikHv** [comment]
Well, your output suggests that you haven't installed "youtube-dl" which is a dependency since Gydl is just a GUI wrapper around it.

What distribution are you using?
